---
# Flannel public IP
# The address that flannel should advertise as how to access the system
# Disabled until https://github.com/coreos/flannel/issues/712 is fixed
# flannel_public_ip: "{{ access_ip|default(ip|default(ansible_default_ipv4.address)) }}"

## interface that should be used for flannel operations
## This is actually an inventory node-level item
# flannel_interface:

# You can choose what type of flannel backend to use
# please refer to flannel's docs : https://github.com/coreos/flannel/blob/master/README.md
flannel_backend_type: "vxlan"

# Advanced flannel backend configuration.
# If you define the entire Backend block as a nested hash called flannel_backend. Then
# this will be used instead of the flannel_backend_type variable.
# For full list of options see docs: https://github.com/coreos/flannel/blob/master/Documentation/backends.md
# Example:
# Configure the flannel with the vxlan backend on an alternative port.
# flannel_backend:
#    Type: "vxlan"
#    Port: 4789

# Limits for apps
flannel_memory_limit: 500M
flannel_cpu_limit: 300m
flannel_memory_requests: 64M
flannel_cpu_requests: 150m

# Legacy directory, will be removed if found.
flannel_cert_dir: /etc/flannel/certs